/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mobi_vhly_demo01_X264Encoder */

#ifndef _Included_mobi_vhly_demo01_X264Encoder
#define _Included_mobi_vhly_demo01_X264Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mobi_vhly_demo01_X264Encoder
 * Method:    encodePreview
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mobi_vhly_demo01_X264Encoder_encodePreview
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
